# Generated by Django 5.0.1 on 2024-01-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Qaladata',
            options={'verbose_name_plural': 'Qala Halyq bazasy'},
        ),
    ]
